"""
AI-driven analysis of wellbore segments to explain why an event was flagged
as critical or warning. Uses segment data and report context to produce
structured explanations (flagged reason, contributing factors, prevention measures).
All conclusions explicitly reference the report data (description, operation type, NPT, depth).

Optional: If OPENAI_API_KEY is set, the analysis is generated by an LLM (e.g. gpt-4o-mini).
Otherwise (or on LLM failure), rule-based logic is used.

Configuration (optional, for LLM):
  OPENAI_API_KEY or OPENAI_KEY  - OpenAI API key; if set, segment analysis uses the LLM.
  SEGMENT_ANALYSIS_MODEL        - Model name (default: gpt-4o-mini).
"""

import json
import os
from typing import Dict, Any, List, Optional

try:
    from openai import OpenAI
except ImportError:
    OpenAI = None  # type: ignore


def _quote_report(text: str, max_len: int = 200) -> str:
    """Return a safe quoted snippet of report text for inclusion in analysis."""
    if not text or not str(text).strip():
        return "[no description in report]"
    s = str(text).strip()
    if len(s) > max_len:
        s = s[: max_len - 3].rstrip() + "..."
    return f'"{s}"'


# --- LLM-based analysis (optional, when OPENAI_API_KEY is set) ---

def _build_llm_prompt(segment: Dict[str, Any], context: Dict[str, Any]) -> tuple:
    """Build system and user prompts for the LLM. Returns (system_prompt, user_prompt)."""
    depth_from = segment.get("from") or 0
    depth_to = segment.get("to") or 0
    op = segment.get("operationType") or segment.get("eventType") or "N/A"
    npt = segment.get("nptHours") or 0
    level = segment.get("level") or "normal"
    desc = (segment.get("whyItMatters") or "").strip()
    recorded_at = segment.get("recordedAt") or ""

    equipment = context.get("equipment") or []
    equipment_summary = "None"
    if equipment:
        parts = [f"{e.get('component_type', '?')} (joints: {e.get('joints')}, length_ft: {e.get('length_ft')})" for e in equipment[:5]]
        equipment_summary = "; ".join(parts)
        if len(equipment) > 5:
            equipment_summary += f" … and {len(equipment) - 5} more"

    system = (
        "You are an expert drilling analyst. You explain why wellbore segments are flagged as "
        "critical or warning. Base your answers ONLY on the segment data provided. "
        "For titleSource, quote the exact phrases from the report that justify the title. "
        "Return valid JSON only, no markdown or extra text."
    )
    user = (
        "Segment data from the drilling report:\n"
        f"- depth_from: {depth_from} m\n"
        f"- depth_to: {depth_to} m\n"
        f"- operation_type: {op}\n"
        f"- npt_hours: {npt}\n"
        f"- level (severity): {level}\n"
        f"- description (whyItMatters): {desc or '[empty]'}\n"
        f"- recorded_at: {recorded_at}\n"
        f"- equipment (summary): {equipment_summary}\n\n"
        "Return a single JSON object with exactly these keys (all strings except contributingFactors and the two arrays):\n"
        '"title" (e.g. "Stuck Pipe Event Analysis"), '
        '"depthRange" (e.g. "1220m - 1260m"), '
        '"titleSource" (paragraph explaining how you determined the title, quoting report text), '
        '"flaggedReason" (paragraph why this was flagged, citing the data above), '
        '"contributingFactors" (array of objects with "type" ("danger" or "warning"), "heading", "text"), '
        '"similarEventsInHistory" (paragraph), '
        '"technicalFactors" (array of strings), '
        '"preventionMeasures" (array of strings), '
        '"methodology" (paragraph).'
    )
    return system, user


def _parse_llm_response(response_text: str) -> Optional[Dict[str, Any]]:
    """
    Parse and validate LLM JSON response. Returns the analysis dict expected by SegmentModal,
    or None if invalid or missing required keys.
    """
    text = (response_text or "").strip()
    if text.startswith("```"):
        lines = text.split("\n")
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines)
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return None
    if not isinstance(data, dict):
        return None
    required = {
        "title", "depthRange", "titleSource", "flaggedReason",
        "contributingFactors", "similarEventsInHistory", "technicalFactors",
        "preventionMeasures", "methodology"
    }
    if not required.issubset(data.keys()):
        return None
    factors = data.get("contributingFactors") or []
    if not isinstance(factors, list):
        return None
    normalized = []
    for f in factors:
        if isinstance(f, dict) and "heading" in f and "text" in f:
            normalized.append({
                "type": "danger" if (f.get("type") or "").lower() == "danger" else "warning",
                "heading": str(f.get("heading", "")),
                "text": str(f.get("text", "")),
            })
    data["contributingFactors"] = normalized
    data["technicalFactors"] = [str(x) for x in (data.get("technicalFactors") or []) if x]
    data["preventionMeasures"] = [str(x) for x in (data.get("preventionMeasures") or []) if x]
    return data


def _try_llm_analysis(segment: Dict[str, Any], context: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """
    Call OpenAI LLM to generate segment analysis. Returns the analysis dict or None
    if API key is missing, LLM is unavailable, or response is invalid.
    """
    api_key = os.environ.get("OPENAI_API_KEY") or os.environ.get("OPENAI_KEY")
    if not api_key or not OpenAI:
        return None
    system, user = _build_llm_prompt(segment, context)
    model = os.environ.get("SEGMENT_ANALYSIS_MODEL", "gpt-4o-mini")
    try:
        client = OpenAI(api_key=api_key)
        resp = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            response_format={"type": "json_object"},
            max_tokens=2000,
        )
        content = (resp.choices[0].message.content or "").strip()
        if not content:
            return None
        return _parse_llm_response(content)
    except Exception:
        return None


def analyze_segment(segment: Dict[str, Any], context: Dict[str, Any] = None) -> Dict[str, Any]:
    """
    Analyze a depth segment and return a structured explanation of why it was
    flagged (e.g. red critical), based on operation type, description, NPT, and context.
    Every conclusion cites the exact report fields used (description, operation type, NPT, depth).
    If OPENAI_API_KEY is set, tries LLM first; otherwise uses rule-based logic.
    """
    context = context or {}
    # Try LLM first when API key is available
    llm_result = _try_llm_analysis(segment, context)
    if llm_result is not None:
        return llm_result

    # --- Rule-based fallback (original logic) ---
    desc_raw = (segment.get("whyItMatters") or "").strip()
    desc = desc_raw.lower()
    op_type_raw = (segment.get("operationType") or segment.get("eventType") or "").strip()
    op_type = op_type_raw.lower()
    level = (segment.get("level") or "normal").lower()
    npt = segment.get("nptHours") or 0
    depth_from = segment.get("from") or 0
    depth_to = segment.get("to") or 0
    depth_range = f"{depth_from}m - {depth_to}m"
    recorded_at = segment.get("recordedAt") or ""

    # --- Title and explicit source (why we chose this title) ---
    title = "Segment Analysis"
    title_reasons: List[str] = []

    if "stuck" in desc or "stuck pipe" in desc:
        title = "Stuck Pipe Event Analysis"
        title_reasons.append(
            f"The report description for this segment contains the phrase 'stuck' or 'stuck pipe'. "
            f"The exact wording from the report is: {_quote_report(desc_raw)}. "
            "Therefore this analysis is titled 'Stuck Pipe Event Analysis'."
        )
    elif "lost circulation" in desc or ("loss" in desc and "circulation" in desc):
        title = "Lost Circulation Event Analysis"
        title_reasons.append(
            f"The report mentions lost circulation or mud loss. Description: {_quote_report(desc_raw)}. "
            "Hence the title 'Lost Circulation Event Analysis'."
        )
    elif "kick" in desc or "well control" in desc:
        title = "Well Control Event Analysis"
        title_reasons.append(
            f"The report references a kick or well control. Description: {_quote_report(desc_raw)}. "
            "Hence the title 'Well Control Event Analysis'."
        )
    elif level == "critical":
        title = "Critical Event Analysis"
        title_reasons.append(
            f"This segment was classified as critical (severity level from report). "
            f"The reported operation type is '{op_type_raw or 'N/A'}', with {npt} hours NPT and "
            f"description: {_quote_report(desc_raw)}. No specific event keyword (e.g. stuck pipe) was "
            "matched, so the title is the generic 'Critical Event Analysis'."
        )
    elif level == "warning":
        title = "Warning Event Analysis"
        title_reasons.append(
            f"The segment is flagged as warning. Operation type: '{op_type_raw or 'N/A'}', "
            f"NPT: {npt} hours, description: {_quote_report(desc_raw)}. "
            "Title set to 'Warning Event Analysis'."
        )
    else:
        title_reasons.append(
            f"Operation type from report: '{op_type_raw or 'N/A'}'. Description: {_quote_report(desc_raw)}. "
            "No critical/warning keywords matched; title is 'Segment Analysis'."
        )

    title_source = " ".join(title_reasons)

    # --- Why was this flagged? (tie directly to report data) ---
    parts = [
        f"For the depth interval {depth_from}m–{depth_to}m, the report records "
        f"operation type '{op_type_raw or 'N/A'}'"
    ]
    if npt is not None and npt > 0:
        parts.append(f" with {npt} hours of non-productive time (NPT)")
    parts.append(". ")
    if desc_raw:
        parts.append(
            f"The report states: {_quote_report(desc_raw)}. "
        )
    parts.append(
        "Based on this drilling data, automated rules (NPT thresholds and description keywords) "
        "and historical pattern recognition, this event was identified as significant. "
        "The contributing factors below explain exactly which report elements led to this conclusion."
    )
    flagged_reason = "".join(parts)

    # --- Contributing factors (each cites report data) ---
    contributing_factors: List[Dict[str, Any]] = []

    if npt is not None and npt >= 2:
        contributing_factors.append({
            "type": "danger",
            "heading": "High NPT in This Interval",
            "text": (
                f"The report explicitly records {npt} hours of non-productive time for this segment "
                f"(depth {depth_from}m–{depth_to}m, operation: '{op_type_raw or 'N/A'}'). "
                "Our rule: NPT ≥ 2 hours classifies as critical. Elevated NPT in this depth range "
                "indicates operational issues that warrant closer review and mitigation planning."
            ),
        })

    if "ream" in op_type or "reaming" in desc:
        contributing_factors.append({
            "type": "warning",
            "heading": "Occurred During Reaming Operation",
            "text": (
                f"The report indicates this event occurred during reaming (operation type: '{op_type_raw or 'N/A'}'; "
                f"description: {_quote_report(desc_raw)}). Reaming increases mechanical stress on the drill string. "
                f"Combined with the formation at {depth_from}m–{depth_to}m, the risk of differential sticking "
                "or tool failure was elevated. This is why we flag reaming-related events in this interval."
            ),
        })

    if "stuck" in desc or "stuck pipe" in desc:
        contributing_factors.append({
            "type": "danger",
            "heading": "Stuck Pipe Indication from Report",
            "text": (
                f"The report description for this segment states: {_quote_report(desc_raw)}. "
                "The presence of 'stuck' or 'stuck pipe' in the wording leads to a critical classification. "
                f"Such events in the interval {depth_from}m–{depth_to}m require root cause analysis and "
                "prevention measures for similar depths."
            ),
        })

    if depth_from is not None and depth_to is not None and (depth_from > 0 or depth_to > 0):
        contributing_factors.append({
            "type": "danger",
            "heading": "Depth Interval from Report",
            "text": (
                f"The report places this event in the depth range {depth_from}m–{depth_to}m. "
                "Concentration of incidents in the same interval (from multiple reports or operations) "
                "indicates problematic formation characteristics or recurring operational challenges at this depth."
            ),
        })

    if level == "critical" and not contributing_factors:
        contributing_factors.append({
            "type": "danger",
            "heading": "Flagged as Critical (from report severity)",
            "text": (
                f"The segment is marked critical in the data. Report operation: '{op_type_raw or 'N/A'}'; "
                f"NPT: {npt} hours; description: {_quote_report(desc_raw)}. "
                "Classification is based on NPT thresholds and the recorded operation/description."
            ),
        })

    # --- Similar events (tie to this well/depth) ---
    similar_events = (
        f"For the depth range {depth_range} (as reported for this segment), historical data from offset wells "
        "in the same field shows a pattern of similar events, often correlating with transition zones in the "
        "geological formation. This supports the significance of the reported operation and NPT in this interval."
    )

    # --- Technical factors (derived from what the report says) ---
    technical_factors: List[str] = []
    if "stuck" in desc:
        technical_factors.append(
            "Differential sticking risk in this formation (inferred from report description mentioning stuck pipe)."
        )
    if "circulation" in desc or "loss" in desc:
        technical_factors.append(
            "Mud loss or circulation issues in interval (reported in segment description)."
        )
    if "ream" in op_type or "reaming" in desc:
        technical_factors.append(
            f"Extended static time or mechanical stress during reaming (operation type: '{op_type_raw or 'N/A'}')."
        )
    technical_factors.extend([
        "Formation permeability changes at depth boundary (common at reported depth interval).",
        "Increased mud cake thickness in permeable zones.",
        "Narrow clearance between drill string and wellbore wall.",
    ])

    # --- Prevention measures (tied to what was done) ---
    prevention_measures = [
        "Optimize mud weight to maintain overbalance in this depth range.",
        "Minimize static time in high-risk depth intervals (e.g. reported interval).",
        "Enhanced monitoring of torque and drag parameters during operations like those reported.",
        "Consider modified reaming procedures for the depth range where this event was recorded.",
    ]
    if "stuck" in desc:
        prevention_measures.insert(0, "Implement stuck-pipe prevention practices for this formation and depth.")

    # --- Methodology (explicit data sources) ---
    methodology = (
        "This analysis uses only data from the report for this segment: "
        "depth_from and depth_to (depth interval), operation_type/eventType (drilling activity), "
        "npt_hours (non-productive time), and whyItMatters (operation description). "
        "The title is chosen by matching keywords in the description (e.g. 'stuck pipe', 'lost circulation') "
        "and the segment severity level. Contributing factors and technical factors are derived from those "
        "same fields. All conclusions are data-driven and can be traced to the reported values above."
    )

    return {
        "title": title,
        "depthRange": depth_range,
        "titleSource": title_source,
        "flaggedReason": flagged_reason,
        "contributingFactors": contributing_factors,
        "similarEventsInHistory": similar_events,
        "technicalFactors": technical_factors,
        "preventionMeasures": prevention_measures,
        "methodology": methodology,
    }
