import { useCallback, useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { apiFetch } from "../api/client";
import "../styles/AiAssistant.css";

export default function AiAssistant() {
  const navigate = useNavigate();
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  /** null = still loading status */
  const [chatStatus, setChatStatus] = useState(null);
  const bottomRef = useRef(null);

  const loadChatStatus = useCallback(async () => {
    const r = await apiFetch("/api/chat/status");
    const d = await r.json().catch(() => ({}));
    if (r.ok) {
      setChatStatus({
        configured: !!d.configured,
        keyNonEmpty: !!d.keyNonEmpty,
        openaiPackageOk: d.openaiPackageOk !== false,
      });
    } else {
      setChatStatus({ configured: false, keyNonEmpty: false, openaiPackageOk: false });
    }
  }, []);

  const aiReady = chatStatus?.configured === true;
  const aiBlocked = chatStatus && !chatStatus.configured;

  useEffect(() => {
    if (!localStorage.getItem("auth")) navigate("/login");
    else loadChatStatus();
  }, [navigate, loadChatStatus]);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, loading]);

  async function send() {
    const text = input.trim();
    if (!text || loading || !aiReady) return;
    setError("");
    setInput("");

    const nextHistory = [...messages, { role: "user", content: text }];
    setMessages(nextHistory);
    setLoading(true);

    try {
      const res = await apiFetch("/api/chat/message", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ messages: nextHistory }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        const detail =
          typeof data.detail === "string"
            ? data.detail
            : Array.isArray(data.detail)
              ? data.detail.map((d) => d.msg || d).join(" ")
              : res.statusText;
        throw new Error(detail || `Request failed (${res.status})`);
      }
      const reply = data.message || "";
      setMessages((prev) => [...prev, { role: "assistant", content: reply }]);
    } catch (e) {
      setError(e.message || "Something went wrong");
      setMessages((prev) => prev.slice(0, -1));
      setInput(text);
    } finally {
      setLoading(false);
    }
  }

  function handleKeyDown(e) {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      send();
    }
  }

  return (
    <div className="aiAssistantPage">
      <header className="aiAssistantHeader">
        <h1 className="aiAssistantTitle">AI Assistant</h1>
        <p className="aiAssistantSub">
          Ask drilling and operations questions. Replies are generated by OpenAI when your backend has an API key set.
        </p>
      </header>

      {aiBlocked && (
        <div className="aiAssistantSetup">
          <strong>The backend still can’t use your OpenAI key.</strong>
          {chatStatus.keyNonEmpty && !chatStatus.openaiPackageOk && (
            <p className="aiAssistantDiag">
              A key value is visible, but the <code className="aiAssistantCode">openai</code> package is missing. Run{" "}
              <code className="aiAssistantCode">pip install -r requirements.txt</code> in your backend environment and restart uvicorn.
            </p>
          )}
          {!chatStatus.keyNonEmpty && (
            <>
              <p className="aiAssistantDiag">
                This server process does not see a non-empty <code className="aiAssistantCode">OPENAI_API_KEY</code> (or{" "}
                <code className="aiAssistantCode">OPENAI_KEY</code>). If you already set it in Windows, fully quit and restart the terminal and uvicorn. Empty
                variables in Windows can also block a <code className="aiAssistantCode">.env</code> file — we now load <code className="aiAssistantCode">.env</code> with override so file values win.
              </p>
              <p>To enable chat replies:</p>
              <ol>
                <li>
                  Put the key in <code className="aiAssistantCode">Implementation/backend/.env</code> as{" "}
                  <code className="aiAssistantCode">OPENAI_API_KEY=sk-…</code> (no spaces around <code className="aiAssistantCode">=</code>), or in{" "}
                  <code className="aiAssistantCode">Implementation/.env</code> (that folder is loaded too).
                </li>
                <li>
                  Key from{" "}
                  <a href="https://platform.openai.com/api-keys" target="_blank" rel="noreferrer">
                    OpenAI
                  </a>
                  .
                </li>
                <li>
                  <code className="aiAssistantCode">pip install -r requirements.txt</code> (includes <code className="aiAssistantCode">python-dotenv</code>).
                </li>
                <li>Restart uvicorn from the folder where you run the app, then click <strong>Check again</strong>.</li>
              </ol>
            </>
          )}
          <button type="button" className="aiAssistantRecheck" onClick={() => loadChatStatus()}>
            Check again
          </button>
        </div>
      )}

      {error && <div className="aiAssistantError">{error}</div>}

      <div className="aiAssistantThread">
        {messages.length === 0 && !loading && (
          <p className="aiAssistantEmpty">
            Try: “What is NPT in drilling?” or “How should I read a daily drilling report?”
          </p>
        )}
        {messages.map((m, i) => (
          <div
            key={`${i}-${m.role}`}
            className={`aiAssistantBubble aiAssistantBubble--${m.role}`}
          >
            <span className="aiAssistantBubbleLabel">
              {m.role === "user" ? "You" : "Assistant"}
            </span>
            <div className="aiAssistantBubbleText">{m.content}</div>
          </div>
        ))}
        {loading && (
          <div className="aiAssistantBubble aiAssistantBubble--assistant">
            <span className="aiAssistantBubbleLabel">Assistant</span>
            <div className="aiAssistantBubbleText aiAssistantTyping">Thinking…</div>
          </div>
        )}
        <div ref={bottomRef} />
      </div>

      <div className="aiAssistantComposer">
        <textarea
          className="aiAssistantInput"
          rows={2}
          placeholder="Type a question… (Enter to send, Shift+Enter for new line)"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          disabled={loading || chatStatus === null || !aiReady}
          aria-label="Message"
        />
        <div className="aiAssistantComposerActions">
          <button
            type="button"
            className="aiAssistantSend"
            onClick={send}
            disabled={loading || !input.trim() || chatStatus === null || !aiReady}
          >
            Send
          </button>
          {messages.length > 0 && (
            <button
              type="button"
              className="aiAssistantClear"
              onClick={() => {
                setMessages([]);
                setError("");
              }}
              disabled={loading}
            >
              Clear chat
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
